---
- name: Install Python 3 via Homebrew
  package:
    name: python3
    state: latest
  when: ansible_os_family == "Darwin"

- name: Add workaround for distutils user installation bug
  copy:
    src: pydistutils.cfg
    dest: ~/.pydistutils.cfg
